version: "3.9"
services:
  api:
    build: .
    ports:
      - "8000:8000"
    env_file:
      - .env
    volumes:
      - ./:/api
  db:
    image: "postgres:15-alpine"
    ports:
      - "5432:5432"
    env_file:
      - .env
